# This is a basic workflow to help you get started with Actions

name: Cub3D-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install necessary linux packages
        run: |
          sudo apt install -y libxext-dev libxrandr-dev libx11-dev libbsd-dev libssl-dev valgrind xvfb
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 4096x2304x16 > /dev/null 2>&1 &

      # Verify cub3d make targets
      - name: Execute make help command
        run: make help
      - name: Execute make command
        run: make
      - name: Execute make clean command
        run: make clean
      - name: Execute make fclean command
        run: make && make fclean
      - name: Execute make re command
        run: make && make re
      # Clone tester
      - name: Clone tester
        run: git clone https://github.com/dalexhd/cub3d-tester.git
      # Check cub3d leaks
      - name: Run cub3D tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 4096x2304x16" make test
        env:
          TERM: xterm
          DISPLAY: :99.0
      # Upload test log
      - name: Upload testing log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: cub3d-tester/report.log
